name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: scp -r -o StrictHostKeyChecking=no . ubuntu@your_server_ip:/home/ubuntu/POKEMEDI-Client/

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@your_server_ip << 'EOF'
            cd /home/ubuntu/POKEMEDI-Client
            yarn install
            yarn build
            sudo systemctl restart nginx
          EOF
